default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: datatables_1_dev

test:
  <<: *default
  database: datatables_1_test

production:
  <<: *default
  database: datatables_1_production
  username: datatables_1
  password: <%= ENV['DATATABLES_1_DATABASE_PASSWORD'] %>
